name: restaurante_dev

services:
  db:
    image: mariadb:11.4
    container_name: restaurante_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', 'mariadb-admin', 'ping', '-h', '127.0.0.1', '-uroot', '-proot']
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    image: node:lts-alpine
    container_name: restaurante_backend
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@db:3306/restaurante
      - DB_HOST=db
      - DB_PORT=3306
      - DBNAMES=restaurante
      - DB_USER=root
      - DB_PASSWORD=root
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: sh -lc "npm i -g pnpm@9 && pnpm install && pnpm run db:generate && pnpm run dev"

  # Simula prod usando el Dockerfile real
  backend_prod:
    build:
      context: .
      dockerfile: Dockerfile # ← usa tu Dockerfile de prod
    container_name: restaurante_backend_prod
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://root:root@db:3306/restaurante
      - DB_HOST=db
      - DB_PORT=3306
      - DBNAMES=restaurante
      - DB_USER=root
      - DB_PASSWORD=root
      - JWT_SECRET=UsetSistemas2025
      - JWT_REFRESH_SECRET=SecretoEnLaUset
      - ALLOWED_ORIGINS=http://localhost:4200,http://localhost:3001
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - prod

volumes:
  db_data:
  node_modules:
